"""
Lakebase Data Provider (PostgreSQL-compatible)

Provides low-latency access to replicated Delta table data via PostgreSQL protocol.
Uses OAuth authentication with Databricks SDK for secure access.

Data is replicated from Unity Catalog Delta tables to Lakebase via Lakeflow Connect.
"""

import os
import logging
import time
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class LakebaseConfig:
    """Configuration for Lakebase Autoscaling (PostgreSQL) provider"""

    # Connection settings (required)
    host: str

    # Autoscaling endpoint config (for OAuth token generation via w.postgres API)
    # Endpoint format: projects/<project>/branches/<branch>/endpoints/<endpoint>
    project: str    # Project name or ID
    branch: str     # Branch name (e.g., 'br-proud-rain-d19jvx11')
    endpoint: str   # Endpoint name (e.g., 'ep-green-feather-d1ziwnzh')

    # Table mapping (required - Unity Catalog -> Lakebase schema path)
    catalog: str  # Unity Catalog catalog
    schema: str   # Unity Catalog schema
    table: str    # Table name

    # Connection settings (optional with defaults)
    port: int = 5432
    database: str = "databricks_postgres"

    @property
    def endpoint_path(self) -> str:
        """Build the full endpoint path for OAuth token generation"""
        return f"projects/{self.project}/branches/{self.branch}/endpoints/{self.endpoint}"

    @classmethod
    def from_env(cls) -> "LakebaseConfig":
        """Create config from environment variables (no prefix - Lakebase is backend-only)"""
        return cls(
            host=os.getenv("LAKEBASE_HOST"),
            port=int(os.getenv("LAKEBASE_PORT", "5432")),
            database=os.getenv("LAKEBASE_DATABASE", "databricks_postgres"),
            project=os.getenv("LAKEBASE_PROJECT"),
            branch=os.getenv("LAKEBASE_BRANCH"),
            endpoint=os.getenv("LAKEBASE_ENDPOINT"),
            catalog=os.getenv("LAKEBASE_CATALOG") or os.getenv("ZEROBUS_CATALOG"),
            schema=os.getenv("LAKEBASE_SCHEMA") or os.getenv("ZEROBUS_SCHEMA"),
            table=os.getenv("LAKEBASE_TABLE") or os.getenv("ZEROBUS_TABLE"),
        )


class LakebaseProvider:
    """
    Data provider for Databricks Lakebase (PostgreSQL-compatible interface).

    Lakebase provides low-latency access to Delta table data via PostgreSQL protocol.
    Authentication is handled via OAuth tokens generated by Databricks SDK.

    Table Mapping:
    - Unity Catalog: catalog.schema.table
    - Lakebase: "catalog.schema"."table" (combined schema path)
    """

    def __init__(self, config: LakebaseConfig):
        self.config = config
        self.connection = None
        self.cursor = None
        self.is_connected = False
        self.last_sql_time_ms = 0  # SQL execution time for last data query
        self.validation_errors: List[str] = []

    @property
    def name(self) -> str:
        return "Lakebase (PostgreSQL)"

    @property
    def full_table_name(self) -> str:
        """
        Full table name in Lakebase format.

        Lakebase uses PostgreSQL's two-level namespace:
        - Database: databricks_postgres (connection level)
        - Schema: Unity Catalog schema name
        - Table: Table name

        So Unity Catalog's catalog.schema.table becomes:
        "schema"."table" in Lakebase SQL (catalog is ignored)
        """
        return f'"{self.config.schema}"."{self.config.table}"'

    def validate_config(self) -> List[str]:
        """Validate Lakebase Autoscaling configuration"""
        errors = []

        if not self.config.host:
            errors.append("LAKEBASE_HOST not configured")

        if not self.config.project:
            errors.append("LAKEBASE_PROJECT not configured (required for OAuth)")

        if not self.config.branch:
            errors.append("LAKEBASE_BRANCH not configured (required for OAuth)")

        if not self.config.endpoint:
            errors.append("LAKEBASE_ENDPOINT not configured (required for OAuth)")

        if not self.config.catalog:
            errors.append("LAKEBASE_CATALOG (or ZEROBUS_CATALOG) not configured")

        if not self.config.schema:
            errors.append("LAKEBASE_SCHEMA (or ZEROBUS_SCHEMA) not configured")

        if not self.config.table:
            errors.append("LAKEBASE_TABLE (or ZEROBUS_TABLE) not configured")

        self.validation_errors = errors
        return errors

    def _get_oauth_token(self) -> tuple:
        """
        Generate OAuth token for Lakebase Autoscaling authentication.
        Uses Databricks SDK postgres API to generate database credentials (1-hour expiry).

        The token is generated for the app's service principal identity.

        Returns:
            tuple: (token, username) - OAuth token and service principal ID
        """
        try:
            from databricks.sdk import WorkspaceClient
        except ImportError as e:
            error_msg = "[Lakebase] Databricks SDK not installed. Add 'databricks-sdk' to requirements.txt"
            logger.error(error_msg)
            self.validation_errors.append(error_msg)
            raise ImportError(error_msg) from e

        endpoint_path = self.config.endpoint_path
        logger.info(f"[Lakebase] Generating OAuth token for endpoint: {endpoint_path}")

        # Temporarily remove DATABRICKS_TOKEN to force OAuth flow
        saved_token = os.environ.pop('DATABRICKS_TOKEN', None)
        try:
            w = WorkspaceClient()
            logger.info("[Lakebase] WorkspaceClient created")

            # Get the current user identity (service principal)
            current_user = w.current_user.me()
            principal_id = current_user.user_name
            logger.info(f"[Lakebase] App identity: {principal_id}")

            # Generate database credential using postgres API (for Autoscaling Lakebase)
            logger.info(f"[Lakebase] Calling w.postgres.generate_database_credential(endpoint={endpoint_path})")
            cred = w.postgres.generate_database_credential(endpoint=endpoint_path)

            logger.info(f"[Lakebase] OAuth token generated, expires: {cred.expire_time}")
            return cred.token, principal_id
        except Exception as e:
            error_msg = f"[Lakebase] Failed to generate database credential: {str(e)}"
            logger.error(error_msg, exc_info=True)
            self.validation_errors.append(error_msg)
            raise
        finally:
            if saved_token:
                os.environ['DATABRICKS_TOKEN'] = saved_token

    def connect(self) -> bool:
        """
        Establish connection to Lakebase via PostgreSQL protocol.
        Uses psycopg with SSL required.
        """
        try:
            import psycopg
        except ImportError as e:
            error_msg = "[Lakebase] psycopg not installed. Add 'psycopg[binary]' to requirements.txt"
            logger.error(error_msg)
            self.validation_errors.append(error_msg)
            return False

        # Get OAuth credentials
        try:
            password, db_user = self._get_oauth_token()
        except Exception as e:
            return False

        logger.info(f"[Lakebase] Connecting to {self.config.host}:{self.config.port}")
        logger.info(f"[Lakebase] User: {db_user}")
        logger.info(f"[Lakebase] Database: {self.config.database}")

        try:
            self.connection = psycopg.connect(
                host=self.config.host,
                port=self.config.port,
                dbname=self.config.database,
                user=db_user,
                password=password,
                sslmode="require",
                autocommit=True
            )
            self.cursor = self.connection.cursor()
            self.is_connected = True
            logger.info("[Lakebase] Connection established successfully")
            return True

        except Exception as e:
            error_str = str(e).lower()
            error_msg = f"[Lakebase] PostgreSQL connection failed: {str(e)}"
            logger.error(error_msg, exc_info=True)
            self.validation_errors.append(error_msg)

            # Add specific context based on error type
            if "authentication" in error_str or "password" in error_str:
                self.validation_errors.append(
                    f"OAuth authentication failed for user '{db_user}'. "
                    f"Check service principal permissions and LAKEBASE_PROJECT/BRANCH/ENDPOINT settings."
                )
            elif "could not connect" in error_str or "connection refused" in error_str:
                self.validation_errors.append(
                    f"Could not reach Lakebase at {self.config.host}:{self.config.port}. "
                    f"Check if instance is running."
                )
            elif "does not exist" in error_str:
                self.validation_errors.append(
                    f"Database '{self.config.database}' does not exist. Check LAKEBASE_DATABASE setting."
                )
            elif "ssl" in error_str:
                self.validation_errors.append(
                    "SSL connection failed. Lakebase requires SSL (sslmode=require)."
                )

            return False

    def close(self) -> None:
        """Close the database connection"""
        if self.cursor:
            self.cursor.close()
        if self.connection:
            self.connection.close()
        self.is_connected = False
        logger.info("[Lakebase] Connection closed")

    def _execute(self, sql: str, params: tuple = None) -> Any:
        """Execute a SQL query with automatic reconnection and transaction recovery"""
        max_retries = 2
        last_error = None

        for attempt in range(max_retries):
            try:
                if not self.is_connected:
                    if not self.connect():
                        raise Exception("[Lakebase] Failed to establish connection")

                if params:
                    self.cursor.execute(sql, params)
                else:
                    self.cursor.execute(sql)
                return self.cursor

            except Exception as e:
                last_error = e
                error_str = str(e).lower()
                logger.warning(f"[Lakebase] Query failed (attempt {attempt + 1}): {e}")

                # Check for transaction aborted error - need to rollback
                if "transaction is aborted" in error_str or "current transaction" in error_str:
                    logger.info("[Lakebase] Transaction aborted, rolling back...")
                    try:
                        self.connection.rollback()
                        logger.info("[Lakebase] Transaction rolled back, retrying...")
                        continue
                    except Exception as rollback_err:
                        logger.warning(f"[Lakebase] Rollback failed: {rollback_err}")

                # Check for auth/connection errors that might be token expiry
                if any(keyword in error_str for keyword in [
                    "authentication", "password", "expired", "connection",
                    "server closed", "broken pipe", "connection reset",
                    "transaction is aborted"
                ]):
                    logger.info("[Lakebase] Attempting reconnection with fresh token...")
                    self.close()
                    self.is_connected = False
                    continue
                else:
                    # Non-recoverable error
                    raise Exception(f"[Lakebase] Query error: {e}")

        # All retries exhausted
        raise Exception(f"[Lakebase] Query failed after {max_retries} attempts: {last_error}")

    def get_count(self) -> int:
        """Get total record count"""
        self._execute(f"SELECT COUNT(*) FROM {self.full_table_name}")
        result = self.cursor.fetchone()
        return result[0] if result else 0

    def get_locations(self, full_trace: bool = False, client_id: str = None, max_points: int = 500) -> List[Dict[str, Any]]:
        """Get device locations for map display

        Args:
            full_trace: If True, return all points for trace visualization (requires client_id)
            client_id: Required when full_trace=True, filters to only this client's data
            max_points: Maximum points to return for full_trace (default 500).
                       If client has more points, SQL subsampling is used to evenly
                       distribute points across the time range using NTILE().
        """
        if full_trace:
            if not client_id:
                raise ValueError("full_trace=True requires a client_id to prevent full table scan")

            # First, get the count to decide if we need subsampling
            self._execute(f"""
                SELECT COUNT(*) FROM {self.full_table_name}
                WHERE client_id = %s
                  AND latitude IS NOT NULL
                  AND longitude IS NOT NULL
                  AND latitude != 0
                  AND longitude != 0
            """, (client_id,))
            total_count = self.cursor.fetchone()[0]

            if total_count <= max_points:
                # No subsampling needed - return all points
                sql_start = time.time()
                self._execute(f"""
                    SELECT
                        client_id,
                        latitude,
                        longitude,
                        timestamp,
                        speed,
                        heading,
                        orientation_beta,
                        orientation_gamma
                    FROM {self.full_table_name}
                    WHERE client_id = %s
                      AND latitude IS NOT NULL
                      AND longitude IS NOT NULL
                      AND latitude != 0
                      AND longitude != 0
                    ORDER BY timestamp DESC
                """, (client_id,))
                self.last_sql_time_ms = int((time.time() - sql_start) * 1000)
            else:
                # PERFORMANCE: Use NTILE() to subsample evenly across time range
                # NTILE(max_points) divides rows into max_points equal buckets by timestamp
                # Then DISTINCT ON (bucket) picks one row per bucket
                # This ensures even distribution across the entire trace duration
                logger.info(f"[Lakebase] Subsampling {total_count} points to {max_points} for client {client_id}")
                sql_start = time.time()
                self._execute(f"""
                    WITH bucketed AS (
                        SELECT
                            client_id,
                            latitude,
                            longitude,
                            timestamp,
                            speed,
                            heading,
                            orientation_beta,
                            orientation_gamma,
                            NTILE(%s) OVER (ORDER BY timestamp) as bucket
                        FROM {self.full_table_name}
                        WHERE client_id = %s
                          AND latitude IS NOT NULL
                          AND longitude IS NOT NULL
                          AND latitude != 0
                          AND longitude != 0
                    )
                    SELECT DISTINCT ON (bucket)
                        client_id,
                        latitude,
                        longitude,
                        timestamp,
                        speed,
                        heading,
                        orientation_beta,
                        orientation_gamma
                    FROM bucketed
                    ORDER BY bucket, timestamp
                """, (max_points, client_id))
                self.last_sql_time_ms = int((time.time() - sql_start) * 1000)
        else:
            # PERFORMANCE OPTIMIZATION: Use DISTINCT ON instead of ROW_NUMBER() window function
            # DISTINCT ON is PostgreSQL-specific and ~3-5x faster for "latest per group" queries
            # because it can stop scanning each group as soon as it finds the first row
            sql_start = time.time()
            self._execute(f"""
                SELECT DISTINCT ON (client_id)
                    client_id,
                    latitude,
                    longitude,
                    timestamp,
                    speed,
                    heading,
                    orientation_beta,
                    orientation_gamma
                FROM {self.full_table_name}
                WHERE latitude IS NOT NULL
                  AND longitude IS NOT NULL
                  AND latitude != 0
                  AND longitude != 0
                ORDER BY client_id, timestamp DESC
            """)
            self.last_sql_time_ms = int((time.time() - sql_start) * 1000)

        results = self.cursor.fetchall()
        locations = []
        for row in results:
            timestamp = row[3]
            if timestamp:
                timestamp_str = timestamp.isoformat() if isinstance(timestamp, datetime) else str(timestamp)
            else:
                timestamp_str = None

            locations.append({
                "uid": row[0],
                "latitude": float(row[1]) if row[1] is not None else None,
                "longitude": float(row[2]) if row[2] is not None else None,
                "last_timestamp": timestamp_str,
                "speed": float(row[4]) if row[4] is not None else None,
                "heading": float(row[5]) if row[5] is not None else None,
                "orientation_beta": float(row[6]) if row[6] is not None else None,
                "orientation_gamma": float(row[7]) if row[7] is not None else None,
            })
        return locations

    def get_clients(self) -> Dict[str, Any]:
        """Get list of all clients with their stats"""
        # PERFORMANCE OPTIMIZATION: Use DISTINCT ON instead of ROW_NUMBER() for latest locations
        # This reduces the query from 2 full table scans to 1 scan + 1 optimized DISTINCT ON
        self._execute(f"""
            WITH client_stats AS (
                SELECT
                    client_id,
                    COUNT(*) as event_count,
                    MIN(timestamp) as first_seen,
                    MAX(timestamp) as last_seen
                FROM {self.full_table_name}
                GROUP BY client_id
            ),
            latest_locations AS (
                SELECT DISTINCT ON (client_id)
                    client_id,
                    latitude,
                    longitude
                FROM {self.full_table_name}
                WHERE latitude IS NOT NULL AND longitude IS NOT NULL
                  AND latitude != 0 AND longitude != 0
                ORDER BY client_id, timestamp DESC
            )
            SELECT
                cs.client_id,
                cs.event_count,
                cs.first_seen,
                cs.last_seen,
                ll.latitude as last_lat,
                ll.longitude as last_lon
            FROM client_stats cs
            LEFT JOIN latest_locations ll ON cs.client_id = ll.client_id
            ORDER BY cs.last_seen DESC
        """)

        results = self.cursor.fetchall()
        now = datetime.now(timezone.utc)
        clients = []

        for row in results:
            last_seen = row[3]
            is_active = False

            if last_seen:
                if isinstance(last_seen, datetime):
                    if last_seen.tzinfo is None:
                        last_seen = last_seen.replace(tzinfo=timezone.utc)
                    time_diff = (now - last_seen).total_seconds()
                    is_active = time_diff < 300  # 5 minutes

            first_seen_str = row[2].isoformat() if isinstance(row[2], datetime) else str(row[2]) if row[2] else None
            last_seen_str = row[3].isoformat() if isinstance(row[3], datetime) else str(row[3]) if row[3] else None

            clients.append({
                "client_id": row[0],
                "event_count": row[1],
                "first_seen": first_seen_str,
                "last_seen": last_seen_str,
                "is_active": is_active,
                "last_location": {
                    "latitude": float(row[4]) if row[4] else None,
                    "longitude": float(row[5]) if row[5] else None,
                },
            })

        return {
            "clients": clients,
            "total": len(clients),
            "active": sum(1 for c in clients if c["is_active"]),
        }

    def get_stream_data(self, limit: int = 50) -> List[Dict[str, Any]]:
        """Get recent sensor readings for streaming table view

        Args:
            limit: Maximum number of records to return
        """
        self._execute(f"""
            SELECT
                client_id,
                timestamp,
                orientation_beta,
                orientation_gamma,
                latitude,
                longitude,
                heading
            FROM {self.full_table_name}
            WHERE latitude IS NOT NULL
              AND longitude IS NOT NULL
              AND latitude != 0
              AND longitude != 0
            ORDER BY timestamp DESC
            LIMIT %s
        """, (limit,))

        results = self.cursor.fetchall()
        records = []
        for row in results:
            timestamp = row[1]
            timestamp_str = timestamp.isoformat() if isinstance(timestamp, datetime) else str(timestamp) if timestamp else None

            records.append({
                "client_id": row[0],
                "timestamp": timestamp_str,
                "pitch": float(row[2]) if row[2] is not None else None,
                "roll": float(row[3]) if row[3] is not None else None,
                "latitude": float(row[4]) if row[4] is not None else None,
                "longitude": float(row[5]) if row[5] is not None else None,
                "heading": float(row[6]) if row[6] is not None else None,
            })
        return records

    def get_status(self) -> Dict[str, Any]:
        """Get detailed system status"""
        record_count = 0
        latest_record = None
        estimated_size_mb = 0
        unique_devices = 0

        if self.is_connected:
            try:
                # Get total count and unique devices
                self._execute(f"""
                    SELECT
                        COUNT(*) as total_records,
                        COUNT(DISTINCT client_id) as unique_devices
                    FROM {self.full_table_name}
                """)
                result = self.cursor.fetchone()
                record_count = result[0]
                unique_devices = result[1]

                # Get latest record
                self._execute(f"""
                    SELECT client_id, timestamp, received_at
                    FROM {self.full_table_name}
                    ORDER BY received_at DESC
                    LIMIT 1
                """)
                result = self.cursor.fetchone()
                if result:
                    timestamp_str = result[1].isoformat() if isinstance(result[1], datetime) else str(result[1]) if result[1] else None
                    received_at_str = result[2].isoformat() if isinstance(result[2], datetime) else str(result[2]) if result[2] else None

                    latest_record = {
                        "client_id": result[0],
                        "timestamp": timestamp_str,
                        "received_at": received_at_str,
                    }

                # Estimate data size (~288 bytes per row with overhead)
                bytes_per_row = 288
                estimated_size_bytes = record_count * bytes_per_row
                estimated_size_mb = round(estimated_size_bytes / (1024 * 1024), 2)

            except Exception as e:
                logger.error(f"[Lakebase] Status query error: {str(e)}")

        return {
            "total_records": record_count,
            "unique_devices": unique_devices,
            "estimated_size_mb": estimated_size_mb,
            "latest_record": latest_record,
        }
